---
#============================ Data
starttime: 2021-12-20T00:00:00
endtime: 2021-12-21T00:00:00
searchWindow: []
# Selected region for downloading stations
center: [56.25, 27.50]
minradius: 0.0
maxradius: 1.0
# Selected region for appyling picker
xlim_degree: [55.00, 58.00]
ylim_degree: [26.00, 29.00]
zlim_degree: [0.0, 50.0]
# Data restriction
networks: [FN, BI]
fdsn_urls: ["http://localhost:8080"]
stations_inv: stations.xml
picks_file: results/picks.csv
preprocess_data: true
#============================ Velocity model
zz: [0.0, 2.0, 4.0, 10.0, 14.0, 19.0, 46.0]
vp: [4.2, 5.4, 5.7,  5.9,  6.1,  6.5,  8.2]
vp_vs_ratio: 1.75
#============================ Picker settings
picker: "PhaseNet" # PhaseNet, EQTransformer
repick_data: true
min_P_probability: 0.3
min_S_probability: 0.3
batch_size: 500
overlap: 3000
model: "original"
model_version: "latest" # "latest" or the version number string.
model_update: false
number_cpu: 5 # Maximum number of CPU cores that will be used. If set to None, total_number_cpu-2 will be used.
#============================ Association settings
associator: "PyOcto" # GaMMA, PyOcto
# GaMMA Associator
use_dbscan: true
method: "BGMM"
useEikonal: true
# DBSCAN
dbscan_eps: 15 # The maximum time between two neighbor picks
dbscan_min_samples: 5 # The number neighbor to be considered as a core point
# Filtering
min_picks_per_eq: 5
min_p_picks_per_eq: 4
min_s_picks_per_eq: 1
max_sigma11: 1.5 # Max phase time residual (s)
max_sigma22: 1.0 # Max phase amplitude residual (in log scale)
max_sigma12: 1.0 # Max covariance term. (Usually not used)
use_amplitude: false
# PyOcto
tolerance: 2.0
association_cutoff_distance: 250
time_before: 300
n_picks: 5
n_p_picks: 4
n_s_picks: 1
n_p_and_s_picks: 1
#============================ Magnitude estimation (SeisComP)
mag_estimation: true
input_mag_file: "hyp.out" # select.out, hyp.out
#============================ Visilization
plotResults: true
nTests: 3
minmaxRes: 2.0 # s
maxDist: 75   # km
statisticsBy: "hypocenter"
#============================ Catalog export
outCatFmt: ["NORDIC", "SC3ML"]
#============================ Cross sections
profiles:
  -
    dx: 5.0
    dy: 20.0
    length: 50.0
    width: 5.0
    z: 30.0
    theta: -30
  -
    dx: 0.0
    dy: 15.0
    length: 50.0
    width: 5.0
    z: 30.0
    theta: -30
  -
    dx: -5.0
    dy: 10.0
    length: 50.0
    width: 5.0
    z: 30.0
    theta: -30
  -
    dx: -10.0
    dy: 5.0
    length: 50.0
    width: 5.0
    z: 30.0
    theta: -30